name: Build
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  image-build:
    name: Image build
    strategy:
      fail-fast: false
    timeout-minutes: 45
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Fix repository permissions
        run: |
          sudo chown -R $(id -u):$(id -g) .

      - name: Install dependencies
        run: |
          sudo apt-get install --yes \
            binutils \
            debian-archive-keyring \
            devscripts \
            make \
            parted \
            pipx \
            qemu-utils \
            build-essential \
            debhelper-compat

      - name: Setup Incus
        run: |
          curl https://pkgs.zabbly.com/get/incus-daily | sudo sh
          sudo chmod 666 /var/lib/incus/unix.socket
          incus admin init --auto

      - name: Setup mkosi
        run: |
          pipx install git+https://github.com/systemd/mkosi.git@v25.3

      - name: Build the images
        run: |
          export PATH="${PATH}:/root/.local/bin"

          (
            cat << EOF
          #!/bin/sh
          echo ${{ github.ref_name }}
          EOF
          ) > mkosi.version

          echo "${{ secrets.SB_CERT }}" > mkosi.crt
          chmod 644 mkosi.crt
          echo "${{ secrets.SB_KEY }}" > mkosi.key
          chmod 600 mkosi.key

          make build-iso

          mkdir upload

          mv mkosi.output/debug.raw upload/
          mv mkosi.output/incus.raw upload/

          mv mkosi.output/IncusOS_${{ github.ref_name }}.raw upload/IncusOS_${{ github.ref_name }}.img
          mv mkosi.output/IncusOS_${{ github.ref_name }}.iso upload/IncusOS_${{ github.ref_name }}.iso
          mv mkosi.output/IncusOS_${{ github.ref_name }}.efi upload/
          mv mkosi.output/IncusOS_${{ github.ref_name }}.usr-x86-64.* upload/
          mv mkosi.output/IncusOS_${{ github.ref_name }}.usr-x86-64-verity.* upload/
          mv mkosi.output/IncusOS_${{ github.ref_name }}.usr-x86-64-verity-sig.* upload/

      - name: Compress the files
        run: |
          cd upload
          for i in *; do
            gzip -9 "${i}"
          done

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: upload/*
          overwrite: true
          file_glob: true
          release_name: ${{ github.ref_name }}
